package enumClasses;

public enum ServerServicesName {

    DISCONNECT,
    PING,
    ADD_ACCOUNT,
    GET_ACCOUNT,
    GET_MOST_POPULAR_SONGS,
    GET_SONG_BY_IDS,
    GET_RECENT_PUPLISCED_ALBUMS,
    GET_ALBUM_SONGS,
    SEARCH_SONGS,
    SEARCH_ALBUMS,
    
    ADD_PLAYLIST,
    ADD_SONG_PLAYLIST,
    REMOVE_SONG_PLAYLIST,
    RENAME_PLAYLIST,
    ADD_COMMENT,
    REMOVE_COMMENT
}
