package enumClasses;

public enum ServerServicesName {

    DISCONNECT,
    PING,
    ADD_ACCOUNT,
    GET_ACCOUNT,
    GET_MOST_POPULAR_SONGS,
    GET_SONG_BY_IDS,
    GET_RECENT_PUPLISCED_ALBUMS,
    GET_ALBUM_SONGS,
    SEARCH_SONGS,
    SEARCH_ALBUMS,
    ADD_PLAYLIST,
    GET_ACCOUNT_PLAYLIST,
    ADD_SONG_PLAYLIST,
    REMOVE_SONG_PLAYLIST, 
    RENAME_PLAYLIST,
    ADD_EMOTION,
    REMOVE_EMOTION,
    GET_COMMENTS_SONG_FOR_ACCOUNT,
    GET_COMMENTS_SONG,
    GET_COMMENTS_ACCOUNT,
    GET_SONG_EMOTION,
    DELETE_PLAYLIST,
    DELETE_ACCOUNT,
    GET_ARTIST_SONGS,
    GET_PLAYLIST_SONGS,
    GET_ALBUM_BY_ID,
    GET_ARTIST_ALBUMS,
    SEARCH_ARTIST,
    GET_ARTIST_BY_ID,
    


}